name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm ci
    - run: npm run lint --if-present
    - run: npm test
